#!/bin/bash
# Helper script to add PREFIX support to qmake-generated Makefiles
# Run this AFTER 'make' to enable 'make PREFIX=/custom/path install'
#
# Important: This must be run AFTER building (make), not just after qmake,
# because subdirectory Makefiles (like app/Makefile) are generated during make.

echo "Adding PREFIX support to Makefiles..."
echo ""

patched_count=0
missing_count=0
issues=()

# Check for .prefix_default.mk in root
if [ ! -f .prefix_default.mk ]; then
    issues+=("ERROR: .prefix_default.mk not found - run 'qmake' first")
    echo "✗ .prefix_default.mk missing - this file is generated by qmake"
    missing_count=$((missing_count + 1))
else
    echo "✓ .prefix_default.mk exists"
fi

# Add include to root Makefile if it exists and doesn't already have it
if [ -f Makefile ]; then
    if ! grep -q "^\-include \.prefix_default\.mk" Makefile; then
        sed -i '1i-include .prefix_default.mk' Makefile
        echo "✓ Patched Makefile"
        patched_count=$((patched_count + 1))
    else
        echo "  Makefile already patched"
    fi
else
    echo "✗ Makefile not found - run 'qmake' first"
    missing_count=$((missing_count + 1))
    issues+=("ERROR: Root Makefile missing - run 'qmake' first")
fi

# Check for app/.prefix_default.mk
if [ ! -f app/.prefix_default.mk ]; then
    issues+=("ERROR: app/.prefix_default.mk not found - run 'qmake' and 'make' first")
    echo "✗ app/.prefix_default.mk missing - this file is generated by qmake"
    missing_count=$((missing_count + 1))
else
    echo "✓ app/.prefix_default.mk exists"
fi

# Add include to app/Makefile if it exists and doesn't already have it
if [ -f app/Makefile ]; then
    if ! grep -q "^\-include \.prefix_default\.mk" app/Makefile; then
        sed -i '1i-include .prefix_default.mk' app/Makefile
        echo "✓ Patched app/Makefile"
        patched_count=$((patched_count + 1))
    else
        echo "  app/Makefile already patched"
    fi
else
    echo "✗ app/Makefile not found - run 'make' first to generate it"
    missing_count=$((missing_count + 1))
    issues+=("ERROR: app/Makefile missing - run 'make' first")
fi

echo ""
echo "=================================================="

# Print any issues
if [ ${#issues[@]} -gt 0 ]; then
    echo "Issues detected:"
    for issue in "${issues[@]}"; do
        echo "  $issue"
    done
    echo ""
fi

if [ $missing_count -gt 0 ]; then
    echo "❌ FAILED: Required files are missing!"
    echo ""
    echo "   The .prefix_default.mk files are generated by qmake and are"
    echo "   removed by 'make clean' or 'make distclean'."
    echo ""
    echo "   Correct order (especially after clean):"
    echo "   1. qmake           # Generates Makefiles and .prefix_default.mk files"
    echo "   2. make            # Builds and generates app/Makefile"
    echo "   3. bash fix-makefiles.sh  ← you are here"
    echo "   4. make PREFIX=/custom/path install"
    echo ""
    echo "   If you ran 'make clean' or 'make distclean', you MUST run"
    echo "   'qmake' again to regenerate the .prefix_default.mk files!"
    echo ""
    exit 1
elif [ $patched_count -eq 0 ]; then
    echo "✓ All Makefiles already patched"
    echo ""
    echo "   You can now run: make PREFIX=/custom/path install"
else
    echo "✓ Success! Patched $patched_count Makefile(s)"
    echo ""
    echo "   You can now run: make PREFIX=/custom/path install"
    echo ""
    echo "   Examples:"
    echo "     make PREFIX=/usr/local install"
    echo "     make PREFIX=/opt install"
fi
